### ISSUE TITLE
Deploy should not fail for non existing instances

### ISSUE THREAD

**Issue by paulmiddelkoop** [msoute/vertx-deploy-tools#11]
If an autoscaling group contains an non existing instance, deployment will fail. It would be nice if non existing instances are ignored.

[ERROR] Failed to execute goal nl.jpoint.vertx-deploy-tools:vertx-deploy-maven-plugin:1.2.0.beta6:deploy-single-as (default-cli) on project deploy: The instance ID 'i-9cc47830' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidInstanceID.NotFound; Request ID: 47167df2-d1e4-4e76-b877-59459c48e3c4) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by msoute** [comment]
This happens if an InStandby instance is termintated outside of the as group, then the as group keeps a reference to the (not existing) instance. It is probably best to put the instance back in service (then aws removes the instance from the group.) After that the maven plugin should recheck if the as-group is in a deployable state before proceeding.
